
name: Prepare new version

on:
  workflow_dispatch:

permissions:
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: "Do the release"
        run: |
          # make release-all
          echo "changes" >> changes

      - name: Import GPG secret key
        run: |
          mkdir -p ~/.gnupg/
          echo "${{ secrets.GPG }}" | base64 --decode > ~/.gnupg/private.key
          gpg --batch --import ~/.gnupg/private.key

      - name: "Commit the new changes"
        run: |
          git config user.name 'Parodos bot'
          git config user.email 'parodos@redhat.com'
          export KEY=$(date +%y%m%d)
          git add .
          git commit -m "NON-issue: bump version on $KEY"


      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          title: "NON-issue: bump version"
