name: Push manifest to release
on:
  release:
    types: ["created"]

permissions:
  contents: write


jobs:
  build:
    name: Publish binaries
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build
      run: |
        mkdir foo/
        echo "hello world" >> foo/release.md
        echo "hello world" >> foo/boo.md
        apt-get install kubectl -y
        kubectl kustomize hack/manifests/base

    - name: Upload manifest to release
      uses: svenstaro/upload-release-action@v2
      with:
        file: foo/release.md
        asset_name: release.md
        tag: ${{ github.ref }}
        overwrite: true
