name: Push manifest to release
on:
  release:
    types: ["created"]

jobs:
  build:
    name: Publish binaries
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build
      run: echo "hello world" >> release.md

    - name: Upload manifest to release
      uses: svenstaro/upload-release-action@v2
      with:
        file: release.md
        asset_name: release
        tag: ${{ github.ref }}
        overwrite: true
